### ISSUE TITLE
Fedora - error prevents starting

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#3] opened 2018-02-24 17:14 UTC
Using Fedora 27 with XFCE desktop, launching from ~/linux-unpacked
```

fs.js:895 Uncaught Error: ENOENT: no such file or directory, mkdir '~/.safe-cms/safe-cms'
    at Object.fs.mkdirSync (fs.js:895:18)
    at file.createDirectory (/home/user/linux-unpacked/resources/app/src/data/file.js:83:12)
    at new file (/home/user/linux-unpacked/resources/app/src/data/file.js:14:14)
    at Object.<anonymous> (/home/user/linux-unpacked/resources/app/src/data/file.js:120:18)
    at Object.<anonymous> (/home/user/linux-unpacked/resources/app/src/data/file.js:121:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by JPL1** [comment] 2018-02-24 17:19
Also happens with Gnome desktop

**Comment by BadCodeShane** [comment] 2018-02-24 17:19
Thanks for this, this is due to a change in version `0.0.2` added to fix a directory permissions issue in Linux environments. I'll fix, rebuild and update the package for you now, I've already fixed it locally.

**Comment by BadCodeShane** [comment] 2018-02-24 19:01
@JPL1 is this issue fixed by https://github.com/badcodeltd/safecms/releases/tag/0.0.3 ?

**Comment by BadCodeShane** [comment] 2018-02-24 19:29
@JPL1 confirmed within the safenet forum that release 0.0.3 fixed this issue, closing this.

**Closed as completed by BadCodeShane** 2018-02-24 19:29 UTC
Labels: bug
