### ISSUE TITLE
No loading indicators when images are uploading 

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#11] opened 2018-02-24 21:45 UTC
Uploaded an image called 'stilldraft.png' to world.hellooooo/stilldraft.png but it is not rendering properly. Converted it to jpg but same applies. Tried in Peruse and Safe Browser.

![jpgtest](https://user-images.githubusercontent.com/12783198/36635406-13d47dd6-19ac-11e8-86ad-60696b86842f.png)

**Edit by** @BadCodeShane:

"This issue is actually another issue - there's no progress indicator while uploading files, so it's easy to assume that the file uploaded already.

We need to add "Uploading, please wait" screens to facilitate this."

**Comment by BadCodeShane** [comment] 2018-02-24 22:16
This issue is actually another issue - there's no progress indicator while uploading files, so it's easy to assume that the file uploaded already.

We need to add "Uploading, please wait" screens to facilitate this.

**Comment by JPL1** [comment] 2018-02-24 23:29
I think this issue was actually caused by the lack of refresh in the upload files page, so the index.html file which I uploaded first was being uploaded to the image URL instead of the image file.

**Comment by BadCodeShane** [comment] 2018-02-24 23:30
Agreed, after our discussion in private. This is caused by the use of `alert()` instead of rendering a `filesEditSuccess` view, similar to the `postEditSuccess` view.

**Comment by BadCodeShane** [comment] 2018-02-25 12:40
This has been fixed in commits:

https://github.com/badcodeltd/safecms/commit/7f9c740f294ae51a263b56c0852ecda352cc4d46
https://github.com/badcodeltd/safecms/commit/f5f77d2fd8da96df3d04c44671ffa48214e2f199
https://github.com/badcodeltd/safecms/commit/7f9c740f294ae51a263b56c0852ecda352cc4d46

This will be released in version 0.0.4

**Comment by BadCodeShane** [comment] 2018-02-25 15:51
Version 0.0.4 is now live, closing this issue.

**Closed as completed by BadCodeShane** 2018-02-25 15:51 UTC
Labels: bug, enhancement, 0.0.4
