### ISSUE TITLE
Posts appear to be published to SAFE but are shown as still being in draft

### ISSUE THREAD

**Issue by JPL1** [badcodeltd/safecms#5] opened 2018-02-24 20:23 UTC
Create a post, publish to SAFE
![firstpost](https://user-images.githubusercontent.com/12783198/36634712-867261e8-19a0-11e8-9552-d7e5f42cc294.png)
Click on the Posts tab  - post is flagged as 'draft'
![stilldraft](https://user-images.githubusercontent.com/12783198/36634721-9cbdc1e0-19a0-11e8-8c29-d1320ea221ec.png)

**Comment by BadCodeShane** [comment] 2018-02-24 20:46
Thanks for this - you're perfectly correct, I'm actually going to close this though as it's a duplicate of an already existing issue here: https://github.com/badcodeltd/safecms/issues/1

**Closed as completed by BadCodeShane** 2018-02-24 20:46 UTC
Labels: bug, duplicate
